name: Set template version

on:
  push:
    branches:
      - feature/*
      - master
  pull_request:
    branches:
      - '*'

jobs:
  determine_version:
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.gitversion.outputs.major }}
      minor: ${{ steps.gitversion.outputs.minor }}
      patch: ${{ steps.gitversion.outputs.patch }}
      majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: '5.x'
      
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.11.0
        with:
          additionalArguments: /overrideconfig major-version-bump-message="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)" /overrideconfig minor-version-bump-message="^(feat)(\\([\\w\\s-]*\\))?:" /overrideconfig patch-version-bump-message="^(build|chore|ci|docs|fix|perf|refactor|revert|style|test)(\\([\\w\\s-]*\\))?:"
      

  
  update_pullrequest:
    runs-on: ubuntu-latest
    needs: determine_version
    if: github.event_name == 'pull_request'
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Expected new version:
              Full: v${{ needs.determine_version.outputs.majorMinorPatch }}
              Major: v${{ needs.determine_version.outputs.major }}
              MajorMinor: v${{ needs.determine_version.outputs.major }}.${{ needs.determine_version.outputs.minor }}
            
  set_version:
    runs-on: ubuntu-latest
    needs: determine_version
    # if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/'))
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upsert major version tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ needs.determine_version.outputs.major }}
          message: "Version v${{ needs.determine_version.outputs.majorMinorPatch }}"
          force_push_tag: true
    
      - name: Create minor version tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ needs.determine_version.outputs.major }}.${{ needs.determine_version.outputs.minor }}
          message: "Version v${{ needs.determine_version.outputs.majorMinorPatch }}"
          force_push_tag: true
      
      - name: Create version tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ needs.determine_version.outputs.majorMinorPatch }}
          message: "Version v${{ needs.determine_version.outputs.majorMinorPatch }}"
          tag_exists_error: false