name: Output Text and in reverse

on:
  workflow_call:
    inputs:
      first_parameter:
        type: string 
        required: true
      second_parameter:
        type: string 
        required: true

jobs:
  output_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: write_output
        run: |
          echo v4

  text_output:
    uses: ChristianPejrup/github-action-templates-playground/.github/workflows/template1.yml@v0
    with:
      first_parameter: ${{ inputs.first_parameter }}
      second_parameter: ${{ inputs.second_parameter }}

  # test_output_reverse:
  #   uses: ./.github/workflows/template2.yml
  #   with:
  #     first_parameter: ${{ inputs.first_parameter }}
  #     second_parameter: ${{ inputs.second_parameter }}
    
